# model building

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

###  import data set

In [2]:
df=pd.read_csv("Credit Card Defaulter Prediction.csv")

## understand the data set

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         30000 non-null  int64
 1   LIMIT_BAL  30000 non-null  int64
 2   SEX        30000 non-null  str
 3   EDUCATION  30000 non-null  str
 4   MARRIAGE   30000 non-null  str
 5   AGE        30000 non-null  int64
 6   PAY_0      30000 non-null  int64
 7   PAY_2      30000 non-null  int64
 8   PAY_3      30000 non-null  int64
 9   PAY_4      30000 non-null  int64
 10  PAY_5      30000 non-null  int64
 11  PAY_6      30000 non-null  int64
 12  BILL_AMT1  30000 non-null  int64
 13  BILL_AMT2  30000 non-null  int64
 14  BILL_AMT3  30000 non-null  int64
 15  BILL_AMT4  30000 non-null  int64
 16  BILL_AMT5  30000 non-null  int64
 17  BILL_AMT6  30000 non-null  int64
 18  PAY_AMT1   30000 non-null  int64
 19  PAY_AMT2   30000 non-null  int64
 20  PAY_AMT3   30000 non-null  int64
 21  PAY_AMT4   30000 non-null  int64
 22  PAY_AMT5   30000 non-null  int64
 23  PAY_AMT6   30000 non-null  int64
 24  default    30000 non-null  str
dtypes: int64(21), str(4)
memory usage: 6.3 MB

In [4]:
df.shape

(30000, 25)

In [5]:
df.describe()

,ID,LIMIT_BAL,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6,BILL_AMT1,...,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
count,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,...,3.000000e+04,30000.000000,30000.000000,30000.000000,30000.000000,3.000000e+04,30000.00000,30000.000000,30000.000000,30000.000000
mean,15000.500000,167484.322667,35.485500,-0.016700,-0.133767,-0.166200,-0.220667,-0.266200,-0.291100,51223.330900,...,4.701315e+04,43262.948967,40311.400967,38871.760400,5663.580500,5.921163e+03,5225.68150,4826.076867,4799.387633,5215.502567
std,8660.398374,129747.661567,9.217904,1.123802,1.197186,1.196868,1.169139,1.133187,1.149988,73635.860576,...,6.934939e+04,64332.856134,60797.155770,59554.107537,16563.280354,2.304087e+04,17606.96147,15666.159744,15278.305679,17777.465775
min,1.000000,10000.000000,21.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-165580.000000,...,-1.572640e+05,-170000.000000,-81334.000000,-339603.000000,0.000000,0.000000e+00,0.00000,0.000000,0.000000,0.000000
25%,7500.750000,50000.000000,28.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,3558.750000,...,2.666250e+03,2326.750000,1763.000000,1256.000000,1000.000000,8.330000e+02,390.00000,296.000000,252.500000,117.750000
50%,15000.500000,140000.000000,34.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,22381.500000,...,2.008850e+04,19052.000000,18104.500000,17071.000000,2100.000000,2.009000e+03,1800.00000,1500.000000,1500.000000,1500.000000
75%,22500.250000,240000.000000,41.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,67091.000000,...,6.016475e+04,54506.000000,50190.500000,49198.250000,5006.000000,5.000000e+03,4505.00000,4013.250000,4031.500000,4000.000000
max,30000.000000,1000000.000000,79.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,964511.000000,...,1.664089e+06,891586.000000,927171.000000,961664.000000,873552.000000,1.684259e+06,896040.00000,621000.000000,426529.000000,528666.000000

In [6]:
df.isnull().sum()

ID           0
LIMIT_BAL    0
SEX          0
EDUCATION    0
MARRIAGE     0
AGE          0
PAY_0        0
PAY_2        0
PAY_3        0
PAY_4        0
PAY_5        0
PAY_6        0
BILL_AMT1    0
BILL_AMT2    0
BILL_AMT3    0
BILL_AMT4    0
BILL_AMT5    0
BILL_AMT6    0
PAY_AMT1     0
PAY_AMT2     0
PAY_AMT3     0
PAY_AMT4     0
PAY_AMT5     0
PAY_AMT6     0
default      0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default
0,1,20000,F,University,Married,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,Y
1,2,120000,F,University,Single,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,Y
2,3,90000,F,University,Single,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,N
3,4,50000,F,University,Married,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,N
4,5,50000,M,University,Married,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,N

In [9]:
df.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6', 'default '],
      dtype='str')

In [10]:
df=df.rename(columns={'default ':'Default'})

In [11]:
# to balance the classes

majority = df[df['Default'] == 'N']
minority = df[df['Default'] == 'Y']

majority_downsampled = majority.sample(
    n=14512,
    random_state=42
)

df = pd.concat([majority_downsampled, minority])
df = df.sample(frac=1, random_state=42)

# define problem statement
- identify the customers who are defalut and no default by previuous bill payments and customer demographic
- Target variable - default
- Classification model

In [12]:
# target and input variables

In [13]:
y=df['Default']
X=df.drop(columns=['ID','SEX','EDUCATION', 'MARRIAGE','Default','AGE'])

In [14]:
# feature selection

In [15]:
# Mutual information for classification
from sklearn. feature_selection import mutual_info_classif
mutual_info=mutual_info_classif(X,y)
mutual_info=pd.Series(mutual_info)
mutual_info.index=X.columns
mutual_info.sort_values(ascending=False)

PAY_0        0.094382
PAY_2        0.060944
PAY_3        0.042664
PAY_5        0.038188
PAY_4        0.033457
PAY_6        0.028917
PAY_AMT1     0.026511
PAY_AMT4     0.021049
PAY_AMT3     0.020109
LIMIT_BAL    0.020057
PAY_AMT2     0.019220
PAY_AMT5     0.015336
PAY_AMT6     0.013553
BILL_AMT1    0.009922
BILL_AMT2    0.007223
BILL_AMT5    0.006444
BILL_AMT4    0.006107
BILL_AMT3    0.005517
BILL_AMT6    0.005415
dtype: float64

In [75]:
df.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6', 'Default'],
      dtype='str')

# train test split

In [16]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,stratify=y)

In [77]:
X_train.shape

(16918, 19)

# data preprocess

In [17]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

X_train_trans=scaler.fit_transform(X_train)
X_test_trans=scaler.transform(X_test)

# base model

### knn model

In [18]:
from sklearn.metrics import classification_report
from sklearn.neighbors import KNeighborsClassifier

In [19]:
from sklearn.neighbors import KNeighborsClassifier

knn_model=KNeighborsClassifier()
knn_model.fit(X_train_trans,y_train)

KNeighborsClassifier()

In [20]:
# prediction
y_pred_knn=knn_model.predict(X_test_trans)

In [21]:
# evaluaion
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score,precision_score,recall_score

knn_accuracy=accuracy_score(y_test,y_pred_knn)
knn_f1 = f1_score(y_test, y_pred_knn, average='macro')
knn_recall = recall_score(y_test, y_pred_knn, average='macro')
knn_precision = precision_score(y_test, y_pred_knn, average='macro')
knn_accuracy

0.7387706855791962

In [22]:
# results
import pandas as pd

results={'Algorithm':['knn'],
         'accuracy':[knn_accuracy],
         'precision':[knn_precision],
         'recall':[knn_recall],
         'f1_score':[knn_f1]}

In [23]:
results=pd.DataFrame(results)

In [24]:
results

  Algorithm  accuracy  precision    recall  f1_score
0       knn  0.738771   0.694131  0.669969  0.678052

# classification report

In [25]:
from sklearn.metrics import classification_report



knn_report=classification_report(y_test, y_pred_knn)
print(knn_report)

              precision    recall  f1-score   support

           N       0.78      0.85      0.82      2903
           Y       0.60      0.49      0.54      1327

    accuracy                           0.74      4230
   macro avg       0.69      0.67      0.68      4230
weighted avg       0.73      0.74      0.73      4230

# Navie_bayes Model

In [26]:
from sklearn.naive_bayes import GaussianNB

In [27]:
gauss_model=GaussianNB()

gauss_model.fit(X_train_trans, y_train)

y_pred_nb = gauss_model.predict(X_test_trans)

In [28]:
# evaluation
gauss_accuracy=accuracy_score(y_test,y_pred_nb)
gauss_f1 = f1_score(y_test, y_pred_nb, average='macro')
gauss_recall = recall_score(y_test, y_pred_nb, average='macro')
gauss_precision = precision_score(y_test, y_pred_nb, average='macro')

In [29]:
results.loc[len(results)] = ["gaussian nb", gauss_accuracy, gauss_precision, gauss_recall,gauss_f1]
results

     Algorithm  accuracy  precision    recall  f1_score
0          knn  0.738771   0.694131  0.669969  0.678052
1  gaussian nb  0.724113   0.683116  0.690587  0.686277

In [30]:
# classification report

naive_report=classification_report(y_test, y_pred_nb)

In [31]:
print(naive_report)

              precision    recall  f1-score   support

           N       0.81      0.78      0.80      2903
           Y       0.56      0.60      0.58      1327

    accuracy                           0.72      4230
   macro avg       0.68      0.69      0.69      4230
weighted avg       0.73      0.72      0.73      4230

# logistic regression

In [32]:
from sklearn.linear_model import LogisticRegression

In [33]:
lr = LogisticRegression()


lr.fit(X_train_trans, y_train)

y_pred_lr =lr.predict(X_test_trans)

In [34]:
# evaluation

logistic_accuracy=accuracy_score(y_test,y_pred_lr)
logistic_f1 = f1_score(y_test, y_pred_lr, average='macro')
logistic_recall = recall_score(y_test, y_pred_lr, average='macro')
logistic_precision = precision_score(y_test, y_pred_lr, average='macro')

In [35]:
logistic_report=classification_report(y_test,y_pred_lr)

In [36]:
print(logistic_report)

              precision    recall  f1-score   support

           N       0.77      0.93      0.84      2903
           Y       0.72      0.38      0.50      1327

    accuracy                           0.76      4230
   macro avg       0.74      0.66      0.67      4230
weighted avg       0.75      0.76      0.74      4230

In [37]:
results.loc[len(results)] = ["logistic Regression", logistic_accuracy, logistic_precision, logistic_recall,logistic_f1]
results

             Algorithm  accuracy  precision    recall  f1_score
0                  knn  0.738771   0.694131  0.669969  0.678052
1          gaussian nb  0.724113   0.683116  0.690587  0.686277
2  logistic Regression  0.760284   0.744965  0.658028  0.671618

# SVM model

In [38]:
from sklearn.svm import SVC


svm = SVC()


svm.fit(X_train_trans, y_train)

y_pred_svm = svm.predict(X_test_trans)

In [39]:
# evaluation

svm_accuracy=accuracy_score(y_test,y_pred_svm)
svm_f1 = f1_score(y_test, y_pred_svm, average='macro')
svm_recall = recall_score(y_test, y_pred_svm, average='macro')
svm_precision = precision_score(y_test, y_pred_svm, average='macro')

In [40]:
results.loc[len(results)] = ["SVM",svm_accuracy , svm_precision, svm_recall,svm_f1]
results

             Algorithm  accuracy  precision    recall  f1_score
0                  knn  0.738771   0.694131  0.669969  0.678052
1          gaussian nb  0.724113   0.683116  0.690587  0.686277
2  logistic Regression  0.760284   0.744965  0.658028  0.671618
3                  SVM  0.762884   0.741527  0.668718  0.683045

In [41]:
# classification report
svm_report=classification_report(y_test,y_pred_svm)

In [42]:
print(svm_report)

              precision    recall  f1-score   support

           N       0.78      0.92      0.84      2903
           Y       0.71      0.42      0.52      1327

    accuracy                           0.76      4230
   macro avg       0.74      0.67      0.68      4230
weighted avg       0.75      0.76      0.74      4230

# random forest

In [43]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=42)



rf.fit(X_train_trans, y_train)

y_pred_rf = rf.predict(X_test_trans)

In [44]:
# evaluation

rf_accuracy=accuracy_score(y_test,y_pred_rf)
rf_f1 = f1_score(y_test, y_pred_rf, average='macro')
rf_recall = recall_score(y_test, y_pred_rf, average='macro')
rf_precision = precision_score(y_test, y_pred_rf, average='macro')

In [45]:
# classification report

from sklearn.metrics import classification_report


forest_report=classification_report(y_test, y_pred_rf)

print(forest_report)

              precision    recall  f1-score   support

           N       0.78      0.90      0.84      2903
           Y       0.68      0.46      0.55      1327

    accuracy                           0.76      4230
   macro avg       0.73      0.68      0.69      4230
weighted avg       0.75      0.76      0.75      4230

In [46]:
results.loc[len(results)] = ["random forest", rf_accuracy, rf_precision, rf_recall,rf_f1]
results

             Algorithm  accuracy  precision    recall  f1_score
0                  knn  0.738771   0.694131  0.669969  0.678052
1          gaussian nb  0.724113   0.683116  0.690587  0.686277
2  logistic Regression  0.760284   0.744965  0.658028  0.671618
3                  SVM  0.762884   0.741527  0.668718  0.683045
4        random forest  0.761466   0.730526  0.679344  0.692522

# Decision Tree

In [47]:
from sklearn.tree import DecisionTreeClassifier


dt = DecisionTreeClassifier(random_state=42)



dt.fit(X_train_trans, y_train)

y_pred_dt = dt.predict(X_test_trans)

In [48]:
# evaluation

dt_accuracy=accuracy_score(y_test,y_pred_dt)
dt_f1 = f1_score(y_test, y_pred_dt, average='macro')
dt_recall = recall_score(y_test, y_pred_dt, average='macro')
dt_precision = precision_score(y_test, y_pred_dt, average='macro')

In [49]:
results.loc[len(results)] = ["decision tree", dt_accuracy, dt_precision, dt_recall,dt_f1]
results

             Algorithm  accuracy  precision    recall  f1_score
0                  knn  0.738771   0.694131  0.669969  0.678052
1          gaussian nb  0.724113   0.683116  0.690587  0.686277
2  logistic Regression  0.760284   0.744965  0.658028  0.671618
3                  SVM  0.762884   0.741527  0.668718  0.683045
4        random forest  0.761466   0.730526  0.679344  0.692522
5        decision tree  0.669504   0.618766  0.620936  0.619757

In [50]:
decision_report=classification_report(y_test, y_pred_dt)

print(decision_report)

              precision    recall  f1-score   support

           N       0.76      0.75      0.76      2903
           Y       0.47      0.49      0.48      1327

    accuracy                           0.67      4230
   macro avg       0.62      0.62      0.62      4230
weighted avg       0.67      0.67      0.67      4230

# boosting

In [51]:
# gradient boosting

In [52]:
from sklearn.ensemble import GradientBoostingClassifier

In [53]:
gb_clf=GradientBoostingClassifier()

gb_clf.fit(X_train_trans,y_train)

# prediction
y_pred_gb=gb_clf.predict(X_test_trans)

In [54]:
# Evaluation
gb_accuracy=accuracy_score(y_test,y_pred_gb)
gb_f1 = f1_score(y_test, y_pred_gb, average='macro')
gb_recall = recall_score(y_test, y_pred_gb, average='macro')
gb_precision = precision_score(y_test, y_pred_gb, average='macro')

In [55]:
results.loc[len(results)] = ["gradient boosting", gb_accuracy, gb_precision, gb_recall,gb_f1]
results

             Algorithm  accuracy  precision    recall  f1_score
0                  knn  0.738771   0.694131  0.669969  0.678052
1          gaussian nb  0.724113   0.683116  0.690587  0.686277
2  logistic Regression  0.760284   0.744965  0.658028  0.671618
3                  SVM  0.762884   0.741527  0.668718  0.683045
4        random forest  0.761466   0.730526  0.679344  0.692522
5        decision tree  0.669504   0.618766  0.620936  0.619757
6    gradient boosting  0.769267   0.752242  0.676028  0.691479

In [56]:
# classification report
grad_report=classification_report(y_test, y_pred_gb)

print(grad_report)

              precision    recall  f1-score   support

           N       0.78      0.93      0.85      2903
           Y       0.73      0.43      0.54      1327

    accuracy                           0.77      4230
   macro avg       0.75      0.68      0.69      4230
weighted avg       0.76      0.77      0.75      4230

# XG_boost

In [57]:
pip install xgboost

Requirement already satisfied: xgboost in c:\Users\Rajasekhar\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.4.1)
Requirement already satisfied: numpy in c:\Users\Rajasekhar\AppData\Local\Programs\Python\Python314\Lib\site-packages (from xgboost) (2.5.2)
Requirement already satisfied: scipy in c:\Users\Rajasekhar\AppData\Local\Programs\Python\Python314\Lib\site-packages (from xgboost) (1.18.1)
Note: you may need to restart the kernel to use updated packages.

In [58]:
from xgboost import XGBClassifier

In [59]:
y = y.map({'N': 0, 'Y': 1})

In [60]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [61]:
xgb=XGBClassifier()

xgb.fit(X_train_trans,y_train)

# prediction
y_pred_xgb=xgb.predict(X_test_trans)

In [62]:
# evaluation

xgb_accuracy=accuracy_score(y_test,y_pred_xgb)
xgb_f1 = f1_score(y_test, y_pred_xgb, average='macro')
xgb_recall = recall_score(y_test, y_pred_xgb, average='macro')
xgb_precision = precision_score(y_test, y_pred_xgb, average='macro')

In [63]:
# results
results.loc[len(results)] = ["XG boost", xgb_accuracy, xgb_precision, xgb_recall,xgb_f1]
results

             Algorithm  accuracy  precision    recall  f1_score
0                  knn  0.738771   0.694131  0.669969  0.678052
1          gaussian nb  0.724113   0.683116  0.690587  0.686277
2  logistic Regression  0.760284   0.744965  0.658028  0.671618
3                  SVM  0.762884   0.741527  0.668718  0.683045
4        random forest  0.761466   0.730526  0.679344  0.692522
5        decision tree  0.669504   0.618766  0.620936  0.619757
6    gradient boosting  0.769267   0.752242  0.676028  0.691479
7             XG boost  0.652009   0.501513  0.500595  0.463359

In [64]:
# classification report

xgb_report=classification_report(y_test,y_pred_xgb)

In [65]:
print(xgb_report)

              precision    recall  f1-score   support

           0       0.69      0.91      0.78      2903
           1       0.32      0.09      0.15      1327

    accuracy                           0.65      4230
   macro avg       0.50      0.50      0.46      4230
weighted avg       0.57      0.65      0.58      4230

### best model selelction
- from all model the best model is gradient boosting it has good f1 nad precision compared to all models

# model pipe line

In [66]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import RandomizedSearchCV
import pickle

# hyperparamter tuning

# get the best model

In [78]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import RandomizedSearchCV

gb_pipe = Pipeline(steps=[
    ("t1", ColumnTransformer(
        transformers=[
            ("t2", StandardScaler(), [0,1,2,3,4,5,6,7,8,9,
                                     10,11,12,13,14,15,16,17,18])
        ]
    )),
    ("t3", GradientBoostingClassifier(random_state=42))
])
tuned_parameters = {
    "t3__n_estimators": [50, 100, 150, 200],
    "t3__learning_rate": [0.01, 0.05, 0.1, 0.2],
    "t3__max_depth": [2, 3, 4, 5],
    "t3__min_samples_split": [2, 5, 10],
    "t3__min_samples_leaf": [1, 2, 4]
}
gb_clf = RandomizedSearchCV(
    estimator=gb_pipe,
    param_distributions=tuned_parameters,
    n_iter=30,
    scoring="f1_macro",
    cv=5,
    random_state=42,
    n_jobs=-1
)

In [80]:
gb_clf.fit(X_train, y_train)

RandomizedSearchCV(cv=5,
                   estimator=Pipeline(steps=[('t1',
                                              ColumnTransformer(transformers=[('t2',
                                                                               StandardScaler(),
                                                                               [0,
                                                                                1,
                                                                                2,
                                                                                3,
                                                                                4,
                                                                                5,
                                                                                6,
                                                                                7,
                                                                                8,
                                                                                9,
                                                                                10,
                                                                                11,
                                                                                12,
                                                                                13,
                                                                                14,
                                                                                15,
                                                                                16,
                                                                                17,
                                                                                18])])),
                                             ('t3',
                                              GradientBoostingClassifier(random_state=42))]),
                   n_iter=30, n_jobs=-1,
                   param_distributions={'t3__learning_rate': [0.01, 0.05, 0.1,
                                                              0.2],
                                        't3__max_depth': [2, 3, 4, 5],
                                        't3__min_samples_leaf': [1, 2, 4],
                                        't3__min_samples_split': [2, 5, 10],
                                        't3__n_estimators': [50, 100, 150,
                                                             200]},
                   random_state=42, scoring='f1_macro')

In [81]:
# prediction
y_pred_gb_best=gb_clf.predict(X_test)

In [82]:
print(gb_clf.best_params_)
print(gb_clf.best_score_)

{'t3__n_estimators': 200, 't3__min_samples_split': 5, 't3__min_samples_leaf': 1, 't3__max_depth': 5, 't3__learning_rate': 0.05}
0.7011308810466292

In [83]:
# evaluation
from sklearn.metrics import classification_report, f1_score

print(classification_report(y_test, y_pred_gb_best))
print("F1 Macro:", f1_score(y_test, y_pred_gb_best, average='macro'))

              precision    recall  f1-score   support

           0       0.78      0.91      0.84      2903
           1       0.69      0.44      0.54      1327

    accuracy                           0.76      4230
   macro avg       0.74      0.68      0.69      4230
weighted avg       0.75      0.76      0.75      4230

F1 Macro: 0.6892000499192468

In [84]:
## converting to binary code

In [85]:
import pickle

with open("credit_model.pkl", "wb") as f:
    pickle.dump(gb_clf, f)

print("Model saved.")

Model saved.