In [1]:
# model building

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

In [3]:
# import data set

In [4]:
df=pd.read_csv("Credit Card Defaulter Prediction.csv")

In [5]:
# understand the data set

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         30000 non-null  int64
 1   LIMIT_BAL  30000 non-null  int64
 2   SEX        30000 non-null  str
 3   EDUCATION  30000 non-null  str
 4   MARRIAGE   30000 non-null  str
 5   AGE        30000 non-null  int64
 6   PAY_0      30000 non-null  int64
 7   PAY_2      30000 non-null  int64
 8   PAY_3      30000 non-null  int64
 9   PAY_4      30000 non-null  int64
 10  PAY_5      30000 non-null  int64
 11  PAY_6      30000 non-null  int64
 12  BILL_AMT1  30000 non-null  int64
 13  BILL_AMT2  30000 non-null  int64
 14  BILL_AMT3  30000 non-null  int64
 15  BILL_AMT4  30000 non-null  int64
 16  BILL_AMT5  30000 non-null  int64
 17  BILL_AMT6  30000 non-null  int64
 18  PAY_AMT1   30000 non-null  int64
 19  PAY_AMT2   30000 non-null  int64
 20  PAY_AMT3   30000 non-null  int64
 21  PAY_AMT4   30000 non-null  int64
 22  PAY_AMT5   30000 non-null  int64
 23  PAY_AMT6   30000 non-null  int64
 24  default    30000 non-null  str
dtypes: int64(21), str(4)
memory usage: 6.3 MB

In [7]:
df.shape

(30000, 25)

In [8]:
df.describe()

,ID,LIMIT_BAL,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6,BILL_AMT1,...,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
count,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,...,3.000000e+04,30000.000000,30000.000000,30000.000000,30000.000000,3.000000e+04,30000.00000,30000.000000,30000.000000,30000.000000
mean,15000.500000,167484.322667,35.485500,-0.016700,-0.133767,-0.166200,-0.220667,-0.266200,-0.291100,51223.330900,...,4.701315e+04,43262.948967,40311.400967,38871.760400,5663.580500,5.921163e+03,5225.68150,4826.076867,4799.387633,5215.502567
std,8660.398374,129747.661567,9.217904,1.123802,1.197186,1.196868,1.169139,1.133187,1.149988,73635.860576,...,6.934939e+04,64332.856134,60797.155770,59554.107537,16563.280354,2.304087e+04,17606.96147,15666.159744,15278.305679,17777.465775
min,1.000000,10000.000000,21.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-165580.000000,...,-1.572640e+05,-170000.000000,-81334.000000,-339603.000000,0.000000,0.000000e+00,0.00000,0.000000,0.000000,0.000000
25%,7500.750000,50000.000000,28.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,3558.750000,...,2.666250e+03,2326.750000,1763.000000,1256.000000,1000.000000,8.330000e+02,390.00000,296.000000,252.500000,117.750000
50%,15000.500000,140000.000000,34.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,22381.500000,...,2.008850e+04,19052.000000,18104.500000,17071.000000,2100.000000,2.009000e+03,1800.00000,1500.000000,1500.000000,1500.000000
75%,22500.250000,240000.000000,41.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,67091.000000,...,6.016475e+04,54506.000000,50190.500000,49198.250000,5006.000000,5.000000e+03,4505.00000,4013.250000,4031.500000,4000.000000
max,30000.000000,1000000.000000,79.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,964511.000000,...,1.664089e+06,891586.000000,927171.000000,961664.000000,873552.000000,1.684259e+06,896040.00000,621000.000000,426529.000000,528666.000000

In [9]:
df.isnull().sum()

ID           0
LIMIT_BAL    0
SEX          0
EDUCATION    0
MARRIAGE     0
AGE          0
PAY_0        0
PAY_2        0
PAY_3        0
PAY_4        0
PAY_5        0
PAY_6        0
BILL_AMT1    0
BILL_AMT2    0
BILL_AMT3    0
BILL_AMT4    0
BILL_AMT5    0
BILL_AMT6    0
PAY_AMT1     0
PAY_AMT2     0
PAY_AMT3     0
PAY_AMT4     0
PAY_AMT5     0
PAY_AMT6     0
default      0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default
0,1,20000,F,University,Married,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,Y
1,2,120000,F,University,Single,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,Y
2,3,90000,F,University,Single,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,N
3,4,50000,F,University,Married,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,N
4,5,50000,M,University,Married,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,N

In [12]:
# columns

In [13]:
df.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6', 'default '],
      dtype='str')

In [14]:
# rename column default

In [15]:
df=df.rename(columns={'default ':'Default'})

# define problem statement
- identify the customers who are defalut and no default by previuous bill payments and customer demographic
- Target variable - default
- Classification model

In [16]:
# target and input variables

In [17]:
y=df['Default']
X=df.drop(columns=['ID','SEX','EDUCATION', 'MARRIAGE','Default','AGE'])

In [18]:
# feature selection

In [19]:
# Mutual information for classification
from sklearn. feature_selection import mutual_info_classif
mutual_info=mutual_info_classif(X,y)
mutual_info=pd.Series(mutual_info)
mutual_info.index=X.columns
mutual_info.sort_values(ascending=False)

PAY_0        0.076321
PAY_2        0.050944
PAY_3        0.036913
PAY_4        0.030784
PAY_5        0.029742
PAY_AMT1     0.025084
PAY_6        0.024688
PAY_AMT3     0.019631
LIMIT_BAL    0.019068
PAY_AMT2     0.016453
PAY_AMT4     0.016273
PAY_AMT5     0.014709
PAY_AMT6     0.013523
BILL_AMT1    0.010219
BILL_AMT2    0.007108
BILL_AMT3    0.006220
BILL_AMT5    0.006066
BILL_AMT6    0.005130
BILL_AMT4    0.004078
dtype: float64

In [20]:
# k best features

In [21]:
# using F_regression test for regression
from sklearn. feature_selection import SelectKBest, f_classif

select_columns=SelectKBest(score_func=f_classif, k=15)
best_features=select_columns.fit(X, y)

# to display best feature names
selected_feature=X.columns [best_features.get_support ()]
print(selected_feature)

Index(['LIMIT_BAL', 'PAY_0', 'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6',
       'BILL_AMT1', 'BILL_AMT2', 'PAY_AMT1', 'PAY_AMT2', 'PAY_AMT3',
       'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6'],
      dtype='str')

In [22]:
# use k best features

In [23]:
X=df[['LIMIT_BAL', 'PAY_0', 'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6',
       'BILL_AMT1', 'BILL_AMT2', 'PAY_AMT1', 'PAY_AMT2', 'PAY_AMT3',
       'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6']]
y=df['Default']

In [24]:
X.head()

,LIMIT_BAL,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6,BILL_AMT1,BILL_AMT2,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
0,20000,2,2,-1,-1,-2,-2,3913,3102,0,689,0,0,0,0
1,120000,-1,2,0,0,0,2,2682,1725,0,1000,1000,1000,0,2000
2,90000,0,0,0,0,0,0,29239,14027,1518,1500,1000,1000,1000,5000
3,50000,0,0,0,0,0,0,46990,48233,2000,2019,1200,1100,1069,1000
4,50000,-1,0,-1,0,0,0,8617,5670,2000,36681,10000,9000,689,679

In [25]:
# train test split

In [26]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

# data preprocess

In [27]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

X_train_trans=scaler.fit_transform(X_train)
X_test_trans=scaler.transform(X_test)

# KNN Model

### hyper parameter tunning

###  Random search

In [28]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.metrics import classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

In [29]:

tuned_parameters = [{'n_neighbors': [i for i in range(1, 51)],
                        'p': [1, 2, 3]}]
clf = RandomizedSearchCV(estimator=KNeighborsClassifier(),
                        param_distributions=tuned_parameters,
                        scoring='f1_macro',
                        cv=5,
                        return_train_score=True,
                        verbose=1)
clf. fit(X_train_trans, y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits

RandomizedSearchCV(cv=5, estimator=KNeighborsClassifier(),
                   param_distributions=[{'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8,
                                                         9, 10, 11, 12, 13, 14,
                                                         15, 16, 17, 18, 19, 20,
                                                         21, 22, 23, 24, 25, 26,
                                                         27, 28, 29, 30, ...],
                                         'p': [1, 2, 3]}],
                   return_train_score=True, scoring='f1_macro', verbose=1)

In [30]:
print("Best parameters set found on train set")
print(clf.best_params_)
print(clf.best_estimator_)
print()

print('Score on Test Data: ', clf. score(X_test, y_test))

Best parameters set found on train set
{'p': 3, 'n_neighbors': 43}
KNeighborsClassifier(n_neighbors=43, p=3)

c:\Users\Rajasekhar\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(

Score on Test Data:  0.4367254975591438

# knn model

In [31]:
from sklearn.neighbors import KNeighborsClassifier

knn_model=KNeighborsClassifier(n_neighbors=31,p=1)
knn_model.fit(X_train_trans,y_train)

KNeighborsClassifier(n_neighbors=31, p=1)

In [32]:
# prediction
knn_y_pred=knn_model.predict(X_test_trans)

In [33]:
# accuracy score

from sklearn.metrics import accuracy_score

knn_accuracy=accuracy_score(y_test,knn_y_pred)
knn_accuracy

0.82

# classification report

In [35]:
from sklearn.metrics import classification_report



knn_report=classification_report(y_test, knn_y_pred)
print(knn_report)

              precision    recall  f1-score   support

           N       0.84      0.94      0.89      4652
           Y       0.67      0.39      0.49      1348

    accuracy                           0.82      6000
   macro avg       0.76      0.67      0.69      6000
weighted avg       0.80      0.82      0.80      6000

# Naive_Bayes Model

### hyper parameter tuning

In [36]:
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import GridSearchCV
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler

In [37]:
transformer = ColumnTransformer(
    transformers=[
        ('num1', StandardScaler(), [0,1,2,3, 4, 5, 6, 7, 8,9,10,11,12,13,14])
    ],
    remainder='passthrough'
)

In [41]:
pipeline = Pipeline([
    ('preprocessor', transformer),
    ('model', GaussianNB())
])

param_grid = {
    'model__var_smoothing': [
        1e-12, 1e-11, 1e-10,
        1e-9, 1e-8, 1e-7,
        1e-6, 1e-5, 1e-4
    ]
}

random_search = RandomizedSearchCV(
    pipeline,
    param_grid,
    cv=5,
    n_iter=9,
    scoring='f1_macro',
    n_jobs=-1
)

random_search.fit(X_train, y_train)

y_pred_nb = random_search.predict(X_test)

print(random_search.best_params_)
print(random_search.best_score_)

# classification report

naive_report=classification_report(y_test, y_pred_nb)

{'model__var_smoothing': 0.0001}
0.639235314370284

In [50]:
# accuracy

from sklearn.metrics import accuracy_score
nb_accuracy=accuracy_score(y_test,y_pred_nb)

nb_accuracy

0.7361666666666666

In [42]:
print(naive_report)

              precision    recall  f1-score   support

           N       0.88      0.76      0.82      4652
           Y       0.44      0.65      0.53      1348

    accuracy                           0.74      6000
   macro avg       0.66      0.71      0.67      6000
weighted avg       0.78      0.74      0.75      6000

# logistic regression

### parameter tuning

In [43]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import RandomizedSearchCV

lr = LogisticRegression(solver='liblinear', max_iter=1000)

param_grid = {
    'penalty': ['l1', 'l2']
}

random_search = RandomizedSearchCV(
    estimator=lr,
    param_distributions=param_grid,
    n_iter=2,
    cv=5,
    scoring='f1_macro',
    random_state=42,
    n_jobs=-1
)

random_search.fit(X_train_trans, y_train)

y_pred_lr = random_search.predict(X_test_trans)

print("Best Parameters:", random_search.best_params_)
print("Best CV Score:", random_search.best_score_)

Best Parameters: {'penalty': 'l1'}
Best CV Score: 0.607251995055187

c:\Users\Rajasekhar\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\Rajasekhar\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:1429: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

In [51]:
# accuracy_score

logistic_accuracy=accuracy_score(y_test,y_pred_lr)
logistic_accuracy

0.8063333333333333

In [44]:
# report
from sklearn.metrics import classification_report

logistic_report=classification_report(y_test,y_pred_lr)

In [46]:
print(logistic_report)

              precision    recall  f1-score   support

           N       0.81      0.98      0.89      4652
           Y       0.73      0.22      0.34      1348

    accuracy                           0.81      6000
   macro avg       0.77      0.60      0.61      6000
weighted avg       0.79      0.81      0.76      6000

# SVM model

In [47]:
from sklearn.svm import SVC
from sklearn.model_selection import RandomizedSearchCV

svm = SVC()

param_grid = {
    'C': [0.01, 0.1, 1, 10, 100]
}

random_search = RandomizedSearchCV(
    estimator=svm,
    param_distributions=param_grid,
    n_iter=5,
    cv=5,
    scoring='f1_macro',
    random_state=42,
    n_jobs=-1
)

random_search.fit(X_train_trans, y_train)

y_pred_svm = random_search.predict(X_test_trans)

print("Best Parameters:", random_search.best_params_)
print("Best CV Score:", random_search.best_score_)

Best Parameters: {'C': 10}
Best CV Score: 0.6733133579160573

In [52]:
# accuracy
svm_accuracy=accuracy_score(y_test,y_pred_svm)
svm_accuracy

0.8243333333333334

In [48]:
# classification report

from sklearn.metrics import classification_report

svm_report=classification_report(y_test,y_pred_svm)

In [49]:
print(svm_report)

              precision    recall  f1-score   support

           N       0.84      0.95      0.89      4652
           Y       0.70      0.38      0.49      1348

    accuracy                           0.82      6000
   macro avg       0.77      0.67      0.69      6000
weighted avg       0.81      0.82      0.80      6000

# Bagging Random Forest

In [53]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV

rf = RandomForestClassifier(random_state=42)

param_grid = {
    'n_estimators': [100, 200, 300, 500],
    'max_depth': [None, 5, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['sqrt', 'log2']
}

random_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_grid,
    n_iter=20,
    cv=5,
    scoring='f1_macro',
    random_state=42,
    n_jobs=-1
)

random_search.fit(X_train_trans, y_train)

y_pred_rf = random_search.predict(X_test_trans)

print("Best Parameters:", random_search.best_params_)
print("Best CV Score:", random_search.best_score_)

Best Parameters: {'n_estimators': 300, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 'log2', 'max_depth': 10}
Best CV Score: 0.676280026794012

In [54]:
# 

from sklearn.metrics import accuracy_score

forest_accuracy=accuracy_score(y_test, y_pred_rf)
forest_accuracy

0.8228333333333333

In [55]:
# classification report

from sklearn.metrics import classification_report


forest_report=classification_report(y_test, y_pred_rf)

print(forest_report)

              precision    recall  f1-score   support

           N       0.84      0.95      0.89      4652
           Y       0.69      0.39      0.50      1348

    accuracy                           0.82      6000
   macro avg       0.77      0.67      0.69      6000
weighted avg       0.81      0.82      0.80      6000

# Decision tree

In [68]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import RandomizedSearchCV

dt = DecisionTreeClassifier(random_state=42)

param_grid = {
    'max_depth': [3, 5, 10, 15, 20, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'criterion': ['gini', 'entropy']
}

random_search = RandomizedSearchCV(
    estimator=dt,
    param_distributions=param_grid,
    n_iter=20,
    cv=5,
    scoring='f1_macro',
    random_state=42,
    n_jobs=-1
)

random_search.fit(X_train_trans, y_train)

y_pred_dt = random_search.predict(X_test_trans)

print("Best Parameters:", random_search.best_params_)
print("Best CV Score:", random_search.best_score_)

Best Parameters: {'min_samples_split': 10, 'min_samples_leaf': 1, 'max_depth': 5, 'criterion': 'gini'}
Best CV Score: 0.6720605569538535

In [70]:
from sklearn.metrics import classification_report

decision_report=classification_report(y_test, y_pred_dt)

print(decision_report)

              precision    recall  f1-score   support

           N       0.84      0.95      0.89      4652
           Y       0.68      0.38      0.49      1348

    accuracy                           0.82      6000
   macro avg       0.76      0.66      0.69      6000
weighted avg       0.80      0.82      0.80      6000

# pipe line

In [78]:
best_model=random_search.best_estimator_

In [79]:
best_model

Pipeline(steps=[('t1',
                 ColumnTransformer(transformers=[('t2', StandardScaler(),
                                                  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9,
                                                   10, 11, 12, 13, 14])])),
                ('t3', GaussianNB(var_smoothing=0.0001))])

In [80]:
best_model.fit(X_train_trans,y_train)

Pipeline(steps=[('t1',
                 ColumnTransformer(transformers=[('t2', StandardScaler(),
                                                  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9,
                                                   10, 11, 12, 13, 14])])),
                ('t3', GaussianNB(var_smoothing=0.0001))])

In [81]:
# pred
y_pred_best=best_model.predict(X_test_trans)

In [83]:
print(classification_report(y_test,y_pred_best))

              precision    recall  f1-score   support

           N       0.88      0.76      0.82      4652
           Y       0.44      0.65      0.53      1348

    accuracy                           0.74      6000
   macro avg       0.66      0.71      0.67      6000
weighted avg       0.78      0.74      0.75      6000

In [84]:
import pickle

In [85]:
with open("model_pipe.pkl","wb")as f:
    pickle.dump(best_model,f)